//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lumires.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_uk_UA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_uk_UA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lumires.Core.Resources.SharedResource.uk-UA", typeof(SharedResource_uk_UA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електрона пошта некоректна.
        /// </summary>
        internal static string CreateProfile_ValidationError_Email_Invalid {
            get {
                return ResourceManager.GetString("CreateProfile_ValidationError_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва акаунту не може бути пустою.
        /// </summary>
        internal static string CreateProfile_ValidationError_Username_Empty {
            get {
                return ResourceManager.GetString("CreateProfile_ValidationError_Username_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва акаунту може складатися тільки з літер, цифр та нижнього підкреслення (3-20).
        /// </summary>
        internal static string CreateProfile_ValidationError_Username_Invalid {
            get {
                return ResourceManager.GetString("CreateProfile_ValidationError_Username_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалося надіслати лист.
        /// </summary>
        internal static string Error_Email_SendFailed {
            get {
                return ResourceManager.GetString("Error_Email_SendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас немає доступу до цього ресурсу.
        /// </summary>
        internal static string Error_Forbidden {
            get {
                return ResourceManager.GetString("Error_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутрішня помилка сервера.
        /// </summary>
        internal static string Error_Internal {
            get {
                return ResourceManager.GetString("Error_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресурс не знайдено.
        /// </summary>
        internal static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виникла помилка.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка автентифікації або відсутні облікові дані..
        /// </summary>
        internal static string Error_Unauthorized {
            get {
                return ResourceManager.GetString("Error_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви не можете встановити більше 4 улюблених фільмів.
        /// </summary>
        internal static string UpdateFavoriteFilms_ValidationError_Length {
            get {
                return ResourceManager.GetString("UpdateFavoriteFilms_ValidationError_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некоретна довжина порядку.
        /// </summary>
        internal static string UpdateFavoriteFilms_ValidationError_Order_Length {
            get {
                return ResourceManager.GetString("UpdateFavoriteFilms_ValidationError_Order_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порядок фільмів повинен бути унікальним.
        /// </summary>
        internal static string UpdateFavoriteFilms_ValidationError_OrderUnique {
            get {
                return ResourceManager.GetString("UpdateFavoriteFilms_ValidationError_OrderUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL аватару повинен бути валідним.
        /// </summary>
        internal static string ValidationError_AvatarUrl_Invalid {
            get {
                return ResourceManager.GetString("ValidationError_AvatarUrl_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис занадто великий.
        /// </summary>
        internal static string ValidationError_Description_TooLong {
            get {
                return ResourceManager.GetString("ValidationError_Description_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звернення до фільму некоректне.
        /// </summary>
        internal static string ValidationError_FilmId_Invalid {
            get {
                return ResourceManager.GetString("ValidationError_FilmId_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звернення до списку некоректне.
        /// </summary>
        internal static string ValidationError_ListId_Invalid {
            get {
                return ResourceManager.GetString("ValidationError_ListId_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг має бути від 0 до 5.
        /// </summary>
        internal static string ValidationError_Rating_Invalid {
            get {
                return ResourceManager.GetString("ValidationError_Rating_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звернення до відгуку некоректне.
        /// </summary>
        internal static string ValidationError_ReviewId_Invalid {
            get {
                return ResourceManager.GetString("ValidationError_ReviewId_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деякі фільми не було знайдено.
        /// </summary>
        internal static string ValidationError_SomeFilms_WereNotFound {
            get {
                return ResourceManager.GetString("ValidationError_SomeFilms_WereNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви повинні надати текст.
        /// </summary>
        internal static string ValidationError_Text_CannotBeNull {
            get {
                return ResourceManager.GetString("ValidationError_Text_CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звернення до треду некоректне.
        /// </summary>
        internal static string ValidationError_ThreadId_Invalid {
            get {
                return ResourceManager.GetString("ValidationError_ThreadId_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва не може бути пустою.
        /// </summary>
        internal static string ValidationError_Title_Empty {
            get {
                return ResourceManager.GetString("ValidationError_Title_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва колекції задовга.
        /// </summary>
        internal static string ValidationError_Title_TooLong {
            get {
                return ResourceManager.GetString("ValidationError_Title_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва закоротка.
        /// </summary>
        internal static string ValidationError_Title_TooShort {
            get {
                return ResourceManager.GetString("ValidationError_Title_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звернення до користувача некоректне.
        /// </summary>
        internal static string ValidationError_UserId_Invalid {
            get {
                return ResourceManager.GetString("ValidationError_UserId_Invalid", resourceCulture);
            }
        }
    }
}
