//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lumires.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_uk_UA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_uk_UA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lumires.Core.Resources.SharedResource.uk-UA", typeof(SharedResource_uk_UA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис колекції занадто великий.
        /// </summary>
        internal static string Collection_ValidationError_Description_TooLong {
            get {
                return ResourceManager.GetString("Collection_ValidationError_Description_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id фільму з колекції некоректний !.
        /// </summary>
        internal static string Collection_ValidationError_MovieId_Invalid {
            get {
                return ResourceManager.GetString("Collection_ValidationError_MovieId_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва колекції не може бути пустою.
        /// </summary>
        internal static string Collection_ValidationError_Title_Empty {
            get {
                return ResourceManager.GetString("Collection_ValidationError_Title_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва колекції задовга ! (Максимальна довжина - 255).
        /// </summary>
        internal static string Collection_ValidationError_Title_TooLong {
            get {
                return ResourceManager.GetString("Collection_ValidationError_Title_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва колекції закоротка ! (Мінімальна довжина - 5).
        /// </summary>
        internal static string Collection_ValidationError_Title_TooShort {
            get {
                return ResourceManager.GetString("Collection_ValidationError_Title_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електрона пошта некоректна.
        /// </summary>
        internal static string CreateProfile_ValidationError_Email_Invalid {
            get {
                return ResourceManager.GetString("CreateProfile_ValidationError_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва акаунту не може бути пустою.
        /// </summary>
        internal static string CreateProfile_ValidationError_Username_Empty {
            get {
                return ResourceManager.GetString("CreateProfile_ValidationError_Username_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва акаунту може складатися тільки з літер, цифр та нижнього підкреслення (3-20).
        /// </summary>
        internal static string CreateProfile_ValidationError_Username_Invalid {
            get {
                return ResourceManager.GetString("CreateProfile_ValidationError_Username_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалося надіслати лист.
        /// </summary>
        internal static string Error_Email_SendFailed {
            get {
                return ResourceManager.GetString("Error_Email_SendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас немає доступу до цього ресурсу.
        /// </summary>
        internal static string Error_Forbidden {
            get {
                return ResourceManager.GetString("Error_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутрішня помилка сервера.
        /// </summary>
        internal static string Error_Internal {
            get {
                return ResourceManager.GetString("Error_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресурс не знайдено.
        /// </summary>
        internal static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виникла помилка.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка автентифікації або відсутні облікові дані..
        /// </summary>
        internal static string Error_Unauthorized {
            get {
                return ResourceManager.GetString("Error_Unauthorized", resourceCulture);
            }
        }
    }
}
