//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lumires.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lumires.Core.Resources.SharedResource.en-US", typeof(SharedResource_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        internal static string CreateProfile_ValidationError_Email_Invalid {
            get {
                return ResourceManager.GetString("CreateProfile_ValidationError_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty.
        /// </summary>
        internal static string CreateProfile_ValidationError_Username_Empty {
            get {
                return ResourceManager.GetString("CreateProfile_ValidationError_Username_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can only contain letters, numbers, and underscores (3-20 characters).
        /// </summary>
        internal static string CreateProfile_ValidationError_Username_Invalid {
            get {
                return ResourceManager.GetString("CreateProfile_ValidationError_Username_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email.
        /// </summary>
        internal static string Error_Email_SendFailed {
            get {
                return ResourceManager.GetString("Error_Email_SendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this resource.
        /// </summary>
        internal static string Error_Forbidden {
            get {
                return ResourceManager.GetString("Error_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        internal static string Error_Internal {
            get {
                return ResourceManager.GetString("Error_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource was not found.
        /// </summary>
        internal static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed or credentials missing.
        /// </summary>
        internal static string Error_Unauthorized {
            get {
                return ResourceManager.GetString("Error_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is too long.
        /// </summary>
        internal static string ValidationError_Description_TooLong {
            get {
                return ResourceManager.GetString("ValidationError_Description_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film reference is invalid.
        /// </summary>
        internal static string ValidationError_FilmId_Invalid {
            get {
                return ResourceManager.GetString("ValidationError_FilmId_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating should be from 0 to 5.
        /// </summary>
        internal static string ValidationError_Rating_Invalid {
            get {
                return ResourceManager.GetString("ValidationError_Rating_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review reference is invalid.
        /// </summary>
        internal static string ValidationError_ReviewId_Invalid {
            get {
                return ResourceManager.GetString("ValidationError_ReviewId_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some films were not found.
        /// </summary>
        internal static string ValidationError_SomeFilms_WereNotFound {
            get {
                return ResourceManager.GetString("ValidationError_SomeFilms_WereNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should provide the text.
        /// </summary>
        internal static string ValidationError_Text_CannotBeNull {
            get {
                return ResourceManager.GetString("ValidationError_Text_CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread reference is invalid.
        /// </summary>
        internal static string ValidationError_ThreadId_Invalid {
            get {
                return ResourceManager.GetString("ValidationError_ThreadId_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be empty.
        /// </summary>
        internal static string ValidationError_Title_Empty {
            get {
                return ResourceManager.GetString("ValidationError_Title_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is too long .
        /// </summary>
        internal static string ValidationError_Title_TooLong {
            get {
                return ResourceManager.GetString("ValidationError_Title_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is too short.
        /// </summary>
        internal static string ValidationError_Title_TooShort {
            get {
                return ResourceManager.GetString("ValidationError_Title_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User reference is invalid.
        /// </summary>
        internal static string ValidationError_UserId_Invalid {
            get {
                return ResourceManager.GetString("ValidationError_UserId_Invalid", resourceCulture);
            }
        }
    }
}
